# Generated by Django 2.0.1 on 2018-06-14 13:43

from django.db import migrations, models
import django.utils.timezone
import sake_web.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0009_alter_user_last_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('email', models.EmailField(blank=True, max_length=254, unique=True, verbose_name='email address')),
                ('first_name', models.CharField(blank=True, max_length=30, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=150, verbose_name='last name')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.Group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.Permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'user',
                'verbose_name_plural': 'users',
            },
            managers=[
                ('objects', sake_web.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='otumami',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=128, verbose_name='おつまみ名')),
            ],
        ),
        migrations.CreateModel(
            name='otumami_with_sake',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=128, verbose_name='名前')),
            ],
        ),
        migrations.CreateModel(
            name='sakes',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128, verbose_name='銘柄')),
                ('creater', models.CharField(blank=True, max_length=128, verbose_name='蔵元')),
                ('region', models.CharField(blank=True, max_length=128, verbose_name='地域')),
                ('created_type', models.CharField(blank=True, max_length=128, verbose_name='製法')),
                ('sake_type', models.CharField(blank=True, max_length=128, verbose_name='種類')),
                ('dosu', models.CharField(blank=True, max_length=128, verbose_name='度数')),
                ('comment', models.CharField(blank=True, max_length=256, verbose_name='説明')),
                ('img_path', models.CharField(blank=True, max_length=128, verbose_name='画像のパス')),
                ('note', models.CharField(blank=True, max_length=256, verbose_name='備考')),
            ],
        ),
        migrations.CreateModel(
            name='user_favorite',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=128, verbose_name='ユーザー名')),
            ],
        ),
    ]
