# Generated by Django 2.0.1 on 2018-06-14 14:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sake_web', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='sakes',
            new_name='sake',
        ),
    ]
